/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Clases.IExplicaciones;
import java.awt.Dimension;

/**
 *
 * @author jrpaz
 */
public final class ExplicacionDeporte extends javax.swing.JFrame implements IExplicaciones{

    /**
     * Creates new form explicaciones
     */
    public ExplicacionDeporte(){
        initComponents();
        this.setSize(new Dimension(420, 300));
        explicacion();
    }

    
    @Override
    public void explicacion(){
        this.mensaje1.setText("Tienes que intentar adivinar la palabra aleatoria,");
        this.mensaje2.setText("para ello tienes 5 oportunidades.");
        this.mensaje3.setText("En este modo de juego la palabra aleatoria tiene que ver con el deporte");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JPanel();
        mensaje1 = new javax.swing.JLabel();
        mensaje2 = new javax.swing.JLabel();
        mensaje3 = new javax.swing.JLabel();

        Main.setMinimumSize(new java.awt.Dimension(400, 300));
        Main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mensaje1.setText("jLabel1");
        mensaje1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Main.add(mensaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 400, 80));

        mensaje2.setText("jLabel1");
        Main.add(mensaje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 400, 70));

        mensaje3.setText("jLabel1");
        Main.add(mensaje3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 400, 50));

        getContentPane().add(Main, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExplicacionDeporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExplicacionDeporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExplicacionDeporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExplicacionDeporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExplicacionDeporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Main;
    private javax.swing.JLabel mensaje1;
    private javax.swing.JLabel mensaje2;
    private javax.swing.JLabel mensaje3;
    // End of variables declaration//GEN-END:variables
}
