/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author alumno
 */
public class WordleGUI extends javax.swing.JFrame {

    /**
     * Creates new form WordleGUI
     */
    public WordleGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        BotonMotorGrupo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Main = new javax.swing.JPanel();
        letras = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Botones = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Main.setLayout(new java.awt.GridLayout(0, 1));

        letras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setMaximumSize(new java.awt.Dimension(250, 250));
        jPanel2.setMinimumSize(new java.awt.Dimension(250, 250));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 250));
        jPanel2.setLayout(new java.awt.GridLayout(4, 4, 4, 4));

        jLabel3.setText("A");
        jLabel3.setToolTipText("");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel3.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel3.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel2.add(jLabel3);

        jLabel4.setText("A");
        jLabel4.setToolTipText("");
        jLabel4.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel4.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel4.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel2.add(jLabel4);

        jLabel5.setText("A");
        jLabel5.setToolTipText("");
        jLabel5.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel5.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel5.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel2.add(jLabel5);

        jLabel7.setText("A");
        jLabel7.setToolTipText("");
        jLabel7.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel7.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel7.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel2.add(jLabel7);

        jLabel8.setText("A");
        jLabel8.setToolTipText("");
        jLabel8.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel8.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel8.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel2.add(jLabel8);

        jLabel9.setText("A");
        jLabel9.setToolTipText("");
        jLabel9.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel9.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel9.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel2.add(jLabel9);

        jLabel10.setText("A");
        jLabel10.setToolTipText("");
        jLabel10.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel10.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel10.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel2.add(jLabel10);

        jLabel11.setText("A");
        jLabel11.setToolTipText("");
        jLabel11.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel11.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel11.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel2.add(jLabel11);

        jLabel13.setText("A");
        jLabel13.setToolTipText("");
        jLabel13.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel13.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel13.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel2.add(jLabel13);

        jLabel14.setText("A");
        jLabel14.setToolTipText("");
        jLabel14.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel14.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel14.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel2.add(jLabel14);

        jLabel15.setText("A");
        jLabel15.setToolTipText("");
        jLabel15.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel15.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel15.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel2.add(jLabel15);

        jLabel16.setText("A");
        jLabel16.setToolTipText("");
        jLabel16.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel16.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel16.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel2.add(jLabel16);

        jLabel17.setText("A");
        jLabel17.setToolTipText("");
        jLabel17.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel17.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel17.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel2.add(jLabel17);

        jLabel19.setText("A");
        jLabel19.setToolTipText("");
        jLabel19.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel19.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel19.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel2.add(jLabel19);

        jLabel20.setText("A");
        jLabel20.setToolTipText("");
        jLabel20.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel20.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel20.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel2.add(jLabel20);

        jLabel21.setText("A");
        jLabel21.setToolTipText("");
        jLabel21.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel21.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel21.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel2.add(jLabel21);

        jLabel22.setText("A");
        jLabel22.setToolTipText("");
        jLabel22.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel22.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel22.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel2.add(jLabel22);

        jLabel23.setText("A");
        jLabel23.setToolTipText("");
        jLabel23.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel23.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel23.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel2.add(jLabel23);

        jLabel2.setText("A");
        jLabel2.setToolTipText("");
        jLabel2.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel2.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel2.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel2.add(jLabel2);

        jLabel1.setText("A");
        jLabel1.setToolTipText("");
        jLabel1.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel1.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel1.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel2.add(jLabel1);

        letras.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

        Main.add(letras);

        Botones.setPreferredSize(new java.awt.Dimension(500, 230));

        jLabel6.setText("jLabel6");
        jLabel6.setMaximumSize(new java.awt.Dimension(60, 20));
        jLabel6.setMinimumSize(new java.awt.Dimension(60, 20));
        jLabel6.setPreferredSize(new java.awt.Dimension(60, 20));

        jLabel12.setText("jLabel12");
        jLabel12.setMaximumSize(new java.awt.Dimension(60, 20));
        jLabel12.setMinimumSize(new java.awt.Dimension(60, 20));
        jLabel12.setPreferredSize(new java.awt.Dimension(60, 20));

        javax.swing.GroupLayout BotonesLayout = new javax.swing.GroupLayout(Botones);
        Botones.setLayout(BotonesLayout);
        BotonesLayout.setHorizontalGroup(
            BotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        BotonesLayout.setVerticalGroup(
            BotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Main.add(Botones);

        jMenu1.setText("Reiniciar");

        jMenuItem1.setText("Reiniciar");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Motor");

        BotonMotorGrupo.add(jRadioButtonMenuItem1);
        jRadioButtonMenuItem1.setText("Test");
        jMenu2.add(jRadioButtonMenuItem1);

        BotonMotorGrupo.add(jRadioButtonMenuItem2);
        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("File");
        jMenu2.add(jRadioButtonMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WordleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WordleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WordleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WordleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WordleGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BotonMotorGrupo;
    private javax.swing.JPanel Botones;
    private javax.swing.JPanel Main;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JPanel letras;
    // End of variables declaration//GEN-END:variables
}
